# Generated by Django 4.1.5 on 2023-01-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adnin',
            new_name='is_admin',
        ),
    ]
